feat: changes

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,7 +1,9 @@
 name: Release Automation
 
 on:
-  workflow_dispatch:
+  push:
+    branches:
+      - master
 
 jobs:
   release:
@@ -9,18 +11,26 @@ jobs:
 
     steps:
       - name: Checkout code
-        uses: actions/checkout@v3
+        uses: actions/checkout@v2
 
       - name: Set up Node.js
         uses: actions/setup-node@v3
         with:
-          node-version: 'latest'  # Set Node.js version to latest
+          node-version: '20'
+
+      - name: Cache npm dependencies
+        uses: actions/cache@v3
+        with:
+          path: ~/.npm
+          key: npm-${{ hashFiles('**/package-lock.json') }}
+          restore-keys: |
+            npm-
 
       - name: Clean npm cache
-        run: npm cache clean --force  # Clean the npm cache
+        run: npm cache clean --force
 
       - name: Install dependencies
-        run: npm ci  # Install dependencies using npm ci
+        run: npm install
 
       - name: Set Git user identity
         run: |
@@ -34,12 +44,7 @@ jobs:
         env:
           TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
           NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
-        run: |
-          npx release-it --verbose || { 
-            echo "Release-it failed"; 
-            cat /home/runner/.npm/_logs/*.log;  # Print npm logs if release fails
-            exit 1; 
-          }
+        run: npx release-it --verbose || { echo "Release failed!"; cat /home/runner/.npm/_logs/*.log; exit 1; }
 
       - name: Notify Success
         if: success()
@@ -47,6 +52,4 @@ jobs:
 
       - name: Notify Failure
         if: failure()
-        run: |
-          echo "Release failed!"
-          cat /home/runner/.npm/_logs/*.log  # Print npm logs on failure
+        run: echo "Release failed!"
